version: "3"

services:
  backend:
    environment:
      FLASK_ENV: "development"
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./src/backend:/backend
    ports:
      - "5000:5000"
  frontend:
    environment:
      WDS_PROXY_API_HOST: "backend"
      WDS_PROXY_API_PORT: "5000"
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./src/frontend:/frontend
    ports:
      - "8080:8080"
