version: "3"

services:
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./src/backend:/backend
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./src/frontend:/frontend
